imports:
  - { resource: config.yml }

monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: all

    sentry:
      type: raven
      dsn: %sentry_dsn%
      level: notice

    all:
      type: group
      members:
        - nested
        - console
        - sentry

    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: error

    console:
      type: console
